baseURL: https://mstekiel.github.io/wedding
title: L&M
theme: vanilla

publishDir: "docs"

defaultContentLanguage: pl
# defaultContentLanguageInSubdir: false
languages:
  pl:
    languageName: Polski
    weight: 1
    params:
      languageNameShort: PL
      languageFlag: 🇵🇱
      languageIcon: /wedding/images/pl.svg
  it:
    languageName: Italiano
    weight: 2
    params:
      languageNameShort: IT
      languageFlag: 🇮🇹
      languageIcon: /wedding/images/it.svg
  en:
    languageName: English
    weight: 3
    params:
      languageNameShort: EN
      languageFlag: 🇬🇧
      languageIcon: /wedding/images/en.svg

# See https://feathericons.com/
# The value of pre is the icon name
# Unicodes:
# poland 🇵🇱
menu:
  nav:
  - name: L&M
    url: /
    weight: 1
    params:
      icon: /wedding/images/home.svg
  - name: trn
    url: /trn/
    weight: 2
    params:
      icon: /wedding/images/trn-logo-small.svg
  - name: waw
    url: /waw/
    weight: 3
    params:
      icon: /wedding/images/waw-logo-small.svg
  - name: gifts
    url: /gifts/
    weight: 4
    params:
      icon: /wedding/images/gift.svg

disableKinds: ["taxonomy"]

params:
  custom_css: css/michal-vanilla.css
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 800px
  dateFormat: 2 Jan, 2006
  homeText: |
    [<img src="/wedding/images/entrance.jpg" id="m_img" width=95%>]({{< ref "destination">}} "Turin wedding plan")
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: true
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    startLevel: 2


enableEmoji: True